"""Add WebsiteProject model

Revision ID: 5ea58ae18a60
Revises: 653423bdb686
Create Date: 2025-05-13 23:09:43.237484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea58ae18a60'
down_revision = '653423bdb686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False),
    sa.Column('site_title', sa.String(length=100), nullable=True),
    sa.Column('favicon_path', sa.String(length=255), nullable=True),
    sa.Column('global_css', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('website_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_project_project_name'), ['project_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_project_project_name'))

    op.drop_table('website_project')
    # ### end Alembic commands ###
