"""Add PageTemplate model

Revision ID: 653423bdb686
Revises: 1730ed1eb26d
Create Date: 2025-05-13 22:33:56.540570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653423bdb686'
down_revision = '1730ed1eb26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_template')
    # ### end Alembic commands ###
