"""Add ProjectPage model and relationship to WebsiteProject

Revision ID: 792a8b4445f5
Revises: 5ea58ae18a60
Create Date: 2025-05-13 23:33:14.533466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792a8b4445f5'
down_revision = '5ea58ae18a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('website_project_id', sa.Integer(), nullable=False),
    sa.Column('page_template_id', sa.Integer(), nullable=False),
    sa.Column('content_data_json', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.String(length=255), nullable=True),
    sa.Column('meta_keywords', sa.String(length=255), nullable=True),
    sa.Column('navbar_order', sa.Integer(), nullable=True),
    sa.Column('show_in_navbar', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_template_id'], ['page_template.id'], ),
    sa.ForeignKeyConstraint(['website_project_id'], ['website_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_project_id', 'slug', name='_website_project_slug_uc')
    )
    with op.batch_alter_table('project_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_page_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_page_slug'))

    op.drop_table('project_page')
    # ### end Alembic commands ###
