"""Add ProjectAsset and NavbarItem models

Revision ID: 8468e50371a2
Revises: 792a8b4445f5
Create Date: 2025-05-14 05:23:39.254960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8468e50371a2'
down_revision = '792a8b4445f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_project_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['website_project_id'], ['website_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_table('navbar_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_project_id', sa.Integer(), nullable=False),
    sa.Column('project_page_id', sa.Integer(), nullable=True),
    sa.Column('link_text', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_page_id'], ['project_page.id'], ),
    sa.ForeignKeyConstraint(['website_project_id'], ['website_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('navbar_item')
    op.drop_table('project_asset')
    # ### end Alembic commands ###
